### ISSUE TITLE
Relation serialization bug

### ISSUE THREAD

**Issue by badaz** [mapado/rest-client-sdk#24] opened 2016-04-01 08:11 UTC
When we try to update entity with relationships, sdk does not serialize relationships properly. In this example walletList is serialized as an array of strings (proper way) although minisiteList is serialized as an array of Minisite objects (thus not serialized?).

In this example, the contract we get has ids for wallets, and json objects for minisites, but if we get ids for minisites too the problem remains the same.

``` php
/**
 * Contract Model
 *
 * @Rest\Entity(key="contracts", repository="Mapado\Component\Ticketing\Model\Repository\ContractRepository")
 */
class Contract extends HasShortId
{
    /**
     * @var integer
     * @Rest\Attribute(name="id", type="string")
     * @Groups({"ticketing"})
     */
    private $id;

    /**
     * walletList
     *
     * @var array
     * @access private
     *
     * @Rest\OneToMany(name="walletList", targetEntity="Wallet")
     * @Groups({"wallet"})
     */
    private $walletList;

    /**
     * minisiteList
     *
     * @var array
     * @access private
     *
     * @Rest\OneToMany(name="minisiteList", targetEntity="Minsite")
     */
    private $minisiteList;
}
```

``` php
/**
 * Minisite Model
 *
 * @Rest\Entity(key="minisites", repository="Mapado\Component\Ticketing\Model\Repository\MinisiteRepository")
 */
class Minisite extends HasShortId
{
    /**
     * id
     *
     * @Rest\Id
     * @Rest\Attribute(name="id", type="string")
     * @Groups({"contract", "ticketing"})
     *
     * @var string
     * @access private
     */
    private $id;

    /**
     * contract
     *
     * @var Contract
     * @access private
     *
     * @Rest\ManyToOne(name="contract", targetEntity="Contract")
     * @Groups({"ticketing"})
     */
    private $contract;
}
```

``` php
/**
 * Wallet Model
 *
 * @Rest\Entity(key="wallets")
 *
 */
class Wallet extends HasShortId
{
    /**
     * @var integer
     *
     * @Rest\Id
     * @Rest\Attribute(name="id", type="string")
     */
    private $id;

    /**
     * contract
     *
     * @var Contract
     * @access private
     *
     * @Rest\ManyToOne(name="contract", targetEntity="Contract")
     * @Groups({"wallet"})
     */
    private $contract;
}
```

GET http://mon-ticketing-de-dev.com:81/v1/contracts/197
=>

``` json
{
  "@context": "/v1/contexts/Contract",
  "@id": "/v1/contracts/197",
  "walletList": [
    "/v1/wallets/165"
  ],
  "minisiteList": [
    {
      "@id": "/v1/minisites/183",
      "@type": "Minisite",
      "slug": "toto",
      "contract": "/v1/contracts/197",
    }
  ],
}
```

**Comment by jdeniau** [comment] 2017-02-02 16:31
Closing because non-reproducable and maybe fixed with latest commits (~0.18)

**Closed by jdeniau** 2017-02-02 16:31 UTC
Labels: bug
